apiVersion: v1
kind: Service
metadata:
  name: tic4303-websecurity
spec:
  type: NodePort
  selector:
    app: tic4303-websecurity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
